baseURL = "https://really.lol"
languageCode = "en-gb"
title = "really.lol"
theme = "reallylol"
buildFuture = true
timeout = 999999
disableKinds = ["sitemap.xml"]

[pagination]
pagerSize = 10

[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
unsafe = true

[related]
[[related.indices]]
name = "tags"
weight = 100

[mediaTypes."application/xml"]
suffixes = ["xml"]

[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "SITEMAP"]
